name: Rails Tests

on:
  pull_request:
    branches:
      - 'master'
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:5
        ports: ["6379:6379"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up RVM
      run: |
        curl -sSL https://get.rvm.io | bash

    - name: Set up Ruby from .ruby-version
      run: |
        source $HOME/.rvm/scripts/rvm
        rvm install $(cat .ruby-version) --binary
        rvm --default use $(cat .ruby-version)

    - name: Install PostgreSQL 11 client
      run: |
        sudo apt-get -yqq install libpq-dev postgresql-client

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-${{ env.cache-name }}-
          yarn-

    - name: Install node modules
      env:
        RAILS_ENV: test
      run: yarn install

    - name: Cache gems
      uses: actions/cache@v3
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install gems
      env:
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rake db:create db:schema:load test

    - name: Run linter
      run: |
        source $HOME/.rvm/scripts/rvm
        bundle exec rake standard
